### $HOME/.bashrc
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
if [ -f ~/.bash.env ]; then
    . ~/.bash.env
fi
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi