---
# - name: APT mise à jour de tous les paquets
#   apt:
#     name: '*'
#     state: latest
#     update_cache: yes
- name: APT DistUpgrade
  apt:
    upgrade: dist
    update_cache: yes

- name: APT installation des paquets
  apt:
    name:
      - bash-completion
      #- bsd-mailx
      - dnsutils
      - bzip2
      - ca-certificates
      - curl
      - haveged
      - htop
      - git
      - gnupg2
      - gnutls-bin
      - iperf3
      #- logrotate
      - nano
      - netcat
      - rsync
      - sudo
      #- syslog-ng
      - tar
      - telnet
      - tmux
      - unzip
      - vim-nox
      - wget
      - xz-utils
    state: latest
    update_cache: yes
  ignore_errors: yes