---
- hosts: all
  remote_user: root
  vars:
    fqdn:
  tasks:

# apt install python-openssl

  - name: openssl SelfSigned creation du repertoire
    file:
      path: /etc/pki/{{ fqdn }}/
      state: directory

  - name: openssl SelfSigned PrivateKey
    openssl_privatekey:
      path: /etc/pki/{{ fqdn }}/privkey1.pem

  - name: openssl SelfSigned CSR
    openssl_csr:
      path: /etc/pki/{{ fqdn }}/certificat.csr
      privatekey_path: /etc/pki/{{ fqdn }}/privkey1.pem
      common_name: "{{ fqdn }}"

  - name: openssl SelfSigned Certificat
    openssl_certificate:
      path: /etc/pki/{{ fqdn }}/cert1.pem
      privatekey_path: /etc/pki/{{ fqdn }}/privkey1.pem
      csr_path: /etc/pki/{{ fqdn }}/certificat.csr
      provider: selfsigned

# openssl req -x509 -sha512 -nodes -days 365 -newkey rsa:4096 -keyout /etc/pki/hote.exemple.net/privkey1.pem -out /etc/pki/hote.exemple.net/cert1.pem -subj '/C=FR/ST=Paris/L=Paris/O=Exemple/OU=SSI/CN=hote.exemple.net/emailAddress=ssi@exemple.net'