---
- name: cockpit-mfa installation des paquets
  yum:
    name:
      - epel-release
      - cockpit
      - google-authenticator
      - qrencode
    state: latest
    update_cache: yes

- name: cockpit-mfa creation d'un OTP
  debug:
    msg: "google-authenticator doit être exécuté pour créer un OTP"

- name: cockpit-mfa modification PAM
  lineinfile:
    path: /etc/pam.d/cockpit
    line: auth required pam_google_authenticator.so
    insertafter: EOF

- name: cockpit-mfa services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  with_items:
    - cockpit.socket
    - cockpit.service
  ignore_errors: yes