---
- name: dns configuration des resolveurs
  copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    content: |
      ### /etc/resolv.conf
      nameserver 80.67.169.12
      nameserver 9.9.9.9
      nameserver ns10.fr.dns.opennic.glue
      nameserver 2001:910:800::12
      nameserver 2620:fe::fe