---
- name: gitconfig
  copy:
    dest: "{{ item }}"
    group: root
    owner: root
    mode: 0644
    content: |
      ### /root/.gitconfig
      [user]
          name =
          email =
      #   signingkey =
      #[commit]
      #  gpgsign = true
      [core]
          editor = vim
      [color]
          ui = auto
      [alias]
          logp = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
          mg = merge --no-ff
          recup = !sh -c 'git branch --track $1 origin/$1' -
      # [http "https://git.domain.tld/"]
      #   sslVerify = false
      # [http "https://github.com/"]
      #   proxy = "http://User:Password@Proxy:Port"
      # [credential]
      #   helper = cache --timeout 30000
  with_items:
    - /root/.gitconfig
    - /etc/skel/.gitconfig