---
- name: kvm installation des paquets
  yum:
    name:
      - qemu-kvm
      - libvirt
      - libvirt-client
      - cockpit
      - cockpit-machines
      - cockpit-bridge
      - cockpit-storaged
    state: latest
    update_cache: yes
  ignore_errors: yes

- name: kvm firewalld cockpit
  firewalld:
    port: 9090/tcp
    state: enabled
    permanent: yes
    immediate: yes

- name: kvm selinux cockpit
  seport:
    ports: 9090/tcp
    proto: tcp
    setype: http_port_t
    state: present

- name: kvm services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  with_items:
    - libvirtd.service
    - cockpit.socket
    - cockpit.service