---
- hosts: all
  remote_user: root
  vars_files: registrar.yml
  tasks:

# Variables : gandi_api_key & gandi_domaine

  - name: yum installation des paquets
    yum:
      name:
        - certbot
        - platform-python-pip
      state: latest
      update_cache: yes
    ignore_errors: yes

  - pip:
      name: certbot-plugin-gandi

  - name: letsencrypt repertoires
    file:
      path: /etc/letsencrypt/key/
      state: directory
      owner: root
      group: root
      mode: '0600'

  - name: gandi key api
    copy:
      dest: /etc/letsencrypt/key/gandi_api.key
      group: root
      owner: root
      mode: 0600
      content: certbot_plugin_gandi:dns_api_key="{{ gandi_api_key }}"

  - name: generation
    # command: certbot certonly --authenticator certbot-plugin-gandi:dns --certbot-plugin-gandi:dns-credentials /etc/letsencrypt/key/gandi_api.key --non-interactive --agree-tos --email letsencrypt@{{ansible_domain}} -d {{ansible_fqdn}}
    command: certbot certonly --authenticator certbot-plugin-gandi:dns --certbot-plugin-gandi:dns-credentials /etc/letsencrypt/key/gandi_api.key --non-interactive --agree-tos --email letsencrypt@"{{ gandi_domaine }}" -d "{{ gandi_domaine }}"