---
- hosts: all
  remote_user: root
  vars:
    # ansible_python_interpreter: /usr/bin/python3
    domaine: vm.lab
    fqdn: filer.vm.lab
    filer: /srv
  tasks:

# update-alternatives --install /usr/bin/python python /usr/bin/python3 10 && # apt install -y aptitude
 
  - name: lighttpd installation
    apt:
      name:
        - lighttpd
        - python3-openssl
      state: latest
      update_cache: yes
    ignore_errors: yes

# openssl req -x509 -sha512 -nodes -days 365 -newkey rsa:4096 -keyout /etc/pki/{{ fqdn }}/privkey1.pem -out /etc/pki/{{ fqdn }}/cert1.pem -subj '/C=FR/L=Paris/O={{ domaine }}/CN={{ fqdn }}/emailAddress=secu@{{ domaine }}'

  - name: openssl creation du repertoire
    file:
      path: /etc/pki/{{ fqdn }}/
      state: directory

  - name: openssl private key
    openssl_privatekey:
      path: /etc/pki/{{ fqdn }}/privkey1.pem

  - name: openssl csr
    openssl_csr:
      path: /etc/pki/{{ fqdn }}/certificat.csr
      privatekey_path: /etc/pki/{{ fqdn }}/privkey1.pem
      common_name: "{{ fqdn }}"

  - name: openssl certificat
    openssl_certificate:
      path: /etc/pki/{{ fqdn }}/cert1.pem
      privatekey_path: /etc/pki/{{ fqdn }}/privkey1.pem
      csr_path: /etc/pki/{{ fqdn }}/certificat.csr
      provider: selfsigned

# curl https://ssl-config.mozilla.org/ffdhe2048.txt

  - name: OpenSSL DH Mozilla
    copy:
      dest: /etc/pki/{{ fqdn }}/ffdhe2048.pem
      group: root
      owner: root
      mode: 0644
      content: |
        -----BEGIN DH PARAMETERS-----
        MIIBCAKCAQEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
        +8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
        87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
        YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
        7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
        ssbzSibBsu/6iGtCOGEoXJf//////////wIBAg==
        -----END DH PARAMETERS-----

  - name: lighttpd 443 {{ filer }}
    copy:
      dest: /etc/lighttpd/lighttpd.conf
      owner: root
      group: root
      mode: 0644
      content: |
        ### /etc/lighttpd/lighttpd.conf
        server.modules = (
        	"mod_indexfile",
        	"mod_access",
        	"mod_alias",
         	"mod_redirect",
        )
        server.upload-dirs              = ( "/var/cache/lighttpd/uploads" )
        server.errorlog                 = "/var/log/lighttpd/error.log"
        server.pid-file                 = "/var/run/lighttpd.pid"
        server.username                 = "www-data"
        server.groupname                = "www-data"
        server.port                     = 80
        server.http-parseopts = (
          "header-strict"               => "enable",
          "host-strict"                 => "enable",
          "host-normalize"              => "enable",
          "url-normalize-unreserved"    => "enable",
          "url-normalize-required"      => "enable",
          "url-ctrls-reject"            => "enable",
          "url-path-2f-decode"          => "enable",
          "url-path-dotseg-remove"      => "enable",
        )
        index-file.names                = ( "index.php", "index.html" )
        url.access-deny                 = ( "~", ".inc" )
        static-file.exclude-extensions  = ( ".php", ".pl", ".fcgi" )
        compress.cache-dir              = "/var/cache/lighttpd/compress/"
        compress.filetype               = ( "application/javascript", "text/css", "text/html", "text/plain" )
        include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
        include_shell "/usr/share/lighttpd/create-mime.conf.pl"
        include "/etc/lighttpd/conf-enabled/*.conf"
        server.modules += (
        	"mod_compress",
        	"mod_dirlisting",
        	"mod_staticfile",
        )
        server.document-root            = "{{ filer }}"
        dir-listing.activate            = "enable"
        dir-listing.hide-dotfiles       = "enable"
        $SERVER["socket"]               == ":443" {
          ssl.engine                    = "enable" 
          ssl.pemfile                   = "/etc/pki/{{ fqdn }}/cert1.pem"
          ssl.privkey                   = "/etc/pki/{{ fqdn }}/privkey1.pem"
          ssl.openssl.ssl-conf-cmd      = ("Protocol" => "ALL, -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, -TLSv1.2")
          ssl.cipher-list               = ""
          ssl.honor-cipher-order        = "disable"
          setenv.add-response-header    = ("Strict-Transport-Security" => "max-age=63072000")
        }
        $HTTP["scheme"]                 == "http" {
          url.redirect                  = ("" => "https://${url.authority}${url.path}${qsa}")
        }

#  - name: Firewalld
#    firewalld:
#      port: "{{ item }}"
#      state: enabled
#      permanent: yes
#      immediate: yes
#    with_items:
#      - 80/tcp
#      - 443/tcp
#    ignore_errors: yes

  - name: lighttpd daemon
    systemd:
      name: lighttpd.service
      state: restarted
      enabled: yes
      masked: no
      daemon_reload: yes
    ignore_errors: yes