---
- name: Locale GB installation de paquets
  yum:
    name:
      - glibc-common
      - glibc-langpack-en
    state: latest
  ignore_errors: yes

- name: Locale GB generation des locales
  locale_gen:
    name: en_GB.UTF-8
    state: present
  ignore_errors: yes

- name: Locale GB edition du fichier de configuration
  copy:
    dest: /etc/environment
    group: root
    owner: root
    mode: 0644
    content: |
      ### /etc/environment
      LANG=en_GB.UTF-8
      LC_CTYPE=en_GB.UTF-8
      LC_NUMERIC="en_GB.UTF-8"
      LC_TIME="en_GB.UTF-8"
      LC_COLLATE="en_GB.UTF-8"
      LC_MONETARY="en_GB.UTF-8"
      LC_MESSAGES="en_GB.UTF-8"
      LC_PAPER="en_GB.UTF-8"
      LC_NAME="en_GB.UTF-8"
      LC_ADDRESS="en_GB.UTF-8"
      LC_TELEPHONE="en_GB.UTF-8"
      LC_MEASUREMENT="en_GB.UTF-8"
      LC_IDENTIFICATION="en_GB.UTF-8"
      LC_ALL=en_GB.UTF-8

- name: Locale GB edition du fichier de configuration
  copy:
    dest: /etc/locale.conf
    group: root
    owner: root
    mode: 0644
    content: |
      ### /etc/locale.conf
      LANG=en_GB.UTF-8

- name: Locale GB configuration systemd
  command: '/usr/bin/localectl set-locale LANG=en_GB.UTF-8'
  ignore_errors: yes

# Fonctionne mais peu recommandé :
# - name: Locale GB edition manuelle script lang.sh
#   blockinfile:
#     path: /etc/profile.d/lang.sh
#     insertafter: EOF
#     block: |
#       export LANG=en_GB.UTF-8
#       export LANGUAGE=en_GB.UTF-8
#       export LC_COLLATE=C
#       export LC_CTYPE=en_GB.UTF-8
# - name: Locale GB edition manuelle script lang.sh
#   command: 'source /etc/profile.d/lang.sh'
#   ignore_errors: yes