---
- name: snap pre-requis
  apt:
    name: snapd
    state: latest
    update_cache: yes
  ignore_errors: yes

- name: snap installations
  snap:
    name:
      - firefox
      - spotify
      - vlc
      - keepassxc
      - tor

- name: snap vscode
  snap:
    name: code
    classic: yes

- name: snap chromium-beta
  snap:
    name: chromium
    channel: latest/beta