---
- hosts: all
  vars_files: vars_files.yml
  tasks:

  - name: nouvel utilisateur
    user:
      name: "{{ utilisateur }}"
      comment: '{{ utilisateur }}@{{ domaine }}'
      uid: "{{ uid }}"
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa
  - name: ed25519
    openssh_keypair:
      path: /home/"{{ utilisateur }}"/.ssh/id_ed25519
      type: ed25519