---
- name: VIMRC pour Debian
  copy:
    dest: /etc/vim/vimrc
    group: root
    owner: root
    mode: 0644
    content: |
      """ /etc/vim/vimrc
      syntax on
      set ruler
      set paste
      set number
      set expandtab
      set nocompatible
      set shiftwidth=4
      set softtabstop=4
      set background=dark