---
- hosts: all
  remote_user: root
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    wireguard_fqdn: wireguard.domain.tld
    wireguard_port: 51820
  tasks:

  - name: wireguard installation enterprise linux
    yum:
      name:
        - elrepo-release
        - epel-release
        - kmod-wireguard
        - wireguard-tools
      state: latest
      update_cache: yes
    when: ansible_facts['os_family'] == "CentOS"

  - name: wireguard creation du repertoire de configuration
    file:
      path: /etc/wireguard/
      state: directory
      mode: 0600

  - name: wireguard generation des clefs
    command: sh -c 'umask 077 /etc/wireguard/ ; wg genkey | tee /etc/wireguard/wg0.key | wg pubkey > /etc/wireguard/wg0.pub'

  - name: wireguard affichage de la clef privee
    command: cat /etc/wireguard/wg0.key
    register: wg_key

  - name: wireguard affichage de la clef publique
    command: cat /etc/wireguard/wg0.pub
    register: wg_pub

  - name: wireguard configuration
    copy:
      dest: /etc/wireguard/wg0.conf
      group: root
      owner: root
      mode: 0600
      content: |
        ### server ---------------------------------------------------------#
        [Interface]
        PrivateKey  = {{wg_key.stdout}}
        ListenPort  = "{{ wireguard_port }}"
        Address     = 10.20.30.1/24
        PostUp      = firewall-cmd --add-port="{{ wireguard_port }}"/udp && firewall-cmd --add-masquerade
        PostDown    = firewall-cmd --remove-port="{{ wireguard_port }}"/udp && firewall-cmd --remove-masquerade
        # [Peer]
        # PublicKey   =
        # AllowedIPs  = 10.20.30.44/32
        # [Peer]
        # PublicKey   =
        # AllowedIPs  = 10.20.30.45/32
        # [Peer]
        # PublicKey   =
        # AllowedIPs  = 10.20.30.46/32
        ### client ---------------------------------------------------------#
        # [Interface]
        # PrivateKey  =
        # Address     = 10.20.30.44/24
        # [Peer]
        # PublicKey   = {{wg_pub.stdout}}
        # Endpoint    = "{{ wireguard_fqdn }}":"{{ wireguard_port }}"
        # PersistentKeepalive = 25
        # AllowedIPs  = 10.20.30.0/24     # split tunneling
        # AllowedIPs  = 0.0.0.0/0         # full tunneling

  - name: wireguard demarrage automaatique du service
    systemd:
      name: wg-quick@wg0.service
      state: started
      enabled: yes
      daemon_reload: yes