---
- hosts: all
  remote_user: root
  vars:
    locale: en_GB.UTF-8
  tasks:

# update-alternatives --install /usr/bin/python python /usr/bin/python3 10 && apt install -y aptitude

  - name: APT mise à jour de tous les paquets
    apt:
      name: '*'
      state: latest
      update_cache: yes
  
  - name: APT DistUpgrade
    apt:
      upgrade: dist
      update_cache: yes
  
  - name: APT installation des paquets
    apt:
      name:
        - bash-completion
        - dnsutils
        - bzip2
        - ca-certificates
        - curl
        - haveged
        - htop
        - git
        - gnupg2
        - gnutls-bin
        - iperf3
        - locales
        - nano
        - netcat
        - rsync
        - sudo
        - tar
        - telnet
        - tmux
        - unzip
        - vim-nox
        - wget
        - xz-utils
      state: latest
      update_cache: yes
    ignore_errors: yes
  
  - name: SSH clefs autorisees pour root
    authorized_key:
      user: root
      state: present
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG6VOB6xka5bO3c87sNYtpWIRpswcD+ZPog8iSweokiM
  
  - name: DNS configuration des resolveurs
    copy:
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
      content: |
        ### /etc/resolv.conf
        nameserver 80.67.169.12
        nameserver 9.9.9.9
        nameserver ns10.fr.dns.opennic.glue
        nameserver 2001:910:800::12
        nameserver 2620:fe::fe
  
  - name: Locale GB generation des locales
    locale_gen:
      name: "{{ locale }}"
      state: present
    ignore_errors: yes
  
  - name: Locale en_GB
    copy:
      dest: /etc/locale.gen
      group: root
      owner: root
      mode: 0644
      content: |
        ### /etc/locale.gen
        "{{ locale }}" UTF-8

  - name: Locale en_GB
    command: /usr/sbin/locale-gen
  
  - name: Locale en_GB
    copy:
      dest: /etc/default/locale
      group: root
      owner: root
      mode: 0644
      content: |
        ### /etc/default/locale
        LC_ALL=C
        # LC_ALL="{{ locale }}"
        LANGUAGE="{{ locale }}"
        LC_CTYPE="{{ locale }}"
        LC_NUMERIC="{{ locale }}"
        LC_TIME="{{ locale }}"
        LC_COLLATE="{{ locale }}"
        LC_MONETARY="{{ locale }}"
        LC_MESSAGES="{{ locale }}"
        LC_PAPER="{{ locale }}"
        LC_NAME="{{ locale }}"
        LC_ADDRESS="{{ locale }}"
        LC_TELEPHONE="{{ locale }}"
        LC_MEASUREMENT="{{ locale }}"
        LC_IDENTIFICATION="{{ locale }}"

  - name: Locale en_GB
    command: /usr/sbin/update-locale

  - name: BASHRC
    copy:
      dest: "{{ item }}"
      group: root
      owner: root
      mode: 0644
      content: |
        ###  ~/.bashrc
        if [ -f /etc/bashrc ]; then
            . /etc/bashrc
        fi
        if [ -f /etc/bash_completion ]; then
            . /etc/bash_completion
        fi
        #LC_ALL=C
        #PATH=/usr/sbin:/usr/bin:/sbin:/bin
        #export PS1="[\u@\h \w]\\$ "
        #export PS1="\[\e[01;34m\]\u\[\e[0m\]\[\e[01;33m\]@\[\e[0m\]\[\e[01;37m\]\h\[\e[0m\]:\[\e[01;32m\]\w\[\e[0m\] \[\e[01;33m\]\$\[\e[0m\] "
        export PS1="\[\e[01;31m\]\u\[\e[0m\]\[\e[01;33m\]@\[\e[0m\]\[\e[01;37m\]\h\[\e[0m\]:\[\e[01;32m\]\w\[\e[0m\] \[\e[01;33m\]\$\[\e[0m\] "
        alias cp="cp --interactive"
        alias mv="mv --interactive"
        alias rm="rm --interactive"
        alias grep="grep --color=auto"
        alias less="less --quiet"
        alias df="df -h"
        alias dfa="df -haT --total"
        alias du="du --human-readable"
        alias ll="ls -lh --color=auto"
        alias lla="ls -lha --color=auto"
        alias lls="ls -lhS --color=auto"
        alias llt="ls -lht --color=auto"
        alias trees="tree -Csh"
        alias grep="grep --color=auto"
        alias ramclean="sysctl -w vm.drop_caches=3"
        alias ipublic="curl https://api.ipify.org ; echo -e ; curl https://api6.ipify.org"
        alias iperf-free="iperf3 -c ping.online.net -p 5208"
        alias heure="date +'%F-%T'"
        alias meteo="curl wttr.in/Paris"
        alias syspatch="yum repolist && yum check-update && yum update -y"
        export HISTSIZE=99999
        export HISTFILESIZE=999999
        export HISTTIMEFORMAT="%F_%T "
        export VISUAL=vim
        export EDITOR="$VISUAL"
        export PAGER="less"
        export LESS_TERMCAP_mb=$'\e[1;31m'
        export LESS_TERMCAP_md=$'\e[1;33m'
        export LESS_TERMCAP_so=$'\e[01;44;37m'
        export LESS_TERMCAP_us=$'\e[01;37m'
        export LESS_TERMCAP_me=$'\e[0m'
        export LESS_TERMCAP_se=$'\e[0m'
        export LESS_TERMCAP_ue=$'\e[0m'
        export GROFF_NO_SGR=1
    with_items:
      - /root/.bashrc
      - /etc/skel/.bashrc

  - name: VIMRC pour Debian
    copy:
      dest: /etc/vim/vimrc
      group: root
      owner: root
      mode: 0644
      content: |
        """ /etc/vim/vimrc
        syntax on
        set ruler
        set paste
        set number
        set expandtab
        set nocompatible
        set shiftwidth=4
        set softtabstop=4
        set background=dark
  
  - name: TMUX
    copy:
      dest: "{{ item }}"
      group: root
      owner: root
      mode: 0644
      content: |
        ###  ~/.tmux.conf
        unbind C-b
        set -g prefix C-a
        bind C-a send-prefix
        set -g history-limit 1000000
        set -g default-terminal 'screen-256color'
        set -g allow-rename off
        set -g base-index 1
        set -g status-position top
        set -g status-fg colour250
        set -g status-bg colour235
        set -g status-attr dim
        set -g pane-active-border-fg colour8
        set -g pane-active-border-bg default
        set -g mouse on
        set -g status-right '#H | %F | %T '
        set-window-option -g window-status-current-fg colour15
        set-window-option -g window-status-current-bg colour0
        bind s set-window-option synchronize-panes
    with_items:
      - /root/.tmux.conf
      - /etc/skel/.tmux.conf
  
  - name: GitConfig
    copy:
      dest: "{{ item }}"
      group: root
      owner: root
      mode: 0644
      content: |
        ### /root/.gitconfig
        [user]
            name =
            email =
        #   signingkey =
        #[commit]
        #  gpgsign = true
        [core]
            editor = vim
        [color]
            ui = auto
        [alias]
            logp = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
            mg = merge --no-ff
            recup = !sh -c 'git branch --track $1 origin/$1' -
        # [http "https://git.domain.tld/"]
        #   sslVerify = false
        # [http "https://github.com/"]
        #   proxy = "http://User:Password@Proxy:Port"
        # [credential]
        #   helper = cache --timeout 30000
    with_items:
      - /root/.gitconfig
      - /etc/skel/.gitconfig

  - name: GRUB reduction de l'attente
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_TIMEOUT'
      line: GRUB_TIMEOUT=1

  - name: GRUB mise a jour
    command: /usr/sbin/update-grub2

  - name: ETHx configuration
    copy:
      dest: /etc/network/interfaces.ethx
      owner: root
      group: root
      mode: 0644
      content: |
        ### /etc/network/interfaces
        source /etc/network/interfaces.d/*
        auto lo
        iface lo inet loopback
        allow-hotplug ethx
        iface ethx inet dhcp
        iface ethx inet6 auto
        # iface ethx inet static
        # address {{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask }}
        # gateway {{ ansible_default_ipv4.gateway }}

  - name: Redemarrage
    reboot:
