---
- hosts: all
  tasks:

# Installation de Debian 11 Bullseye avec Gnome Core sur un hôte physique.
# update-alternatives --install /usr/bin/python python /usr/bin/python3 10 && apt install -y aptitude

  - name: APT mise à jour de tous les paquets
    apt:
      name: '*'
      state: latest
      update_cache: yes

  - name: APT sources
    copy:
      dest: /etc/apt/sources.list
      group: root
      owner: root
      mode: 0644
      content: |
        ### /etc/apt/sources.list
        deb https://deb.debian.org/debian bullseye main contrib non-free
        deb http://security.debian.org/debian-security bullseye-security main contrib non-free
        deb https://deb.debian.org/debian bullseye-updates main contrib non-free
        # deb https://www.deb-multimedia.org bullseye main non-free

  - name: APT DistUpgrade
    apt:
      upgrade: dist
      update_cache: yes

  - name: Installation des firmwares
    apt:
      name:
        - firmware-linux
        - firmware-linux-free
        - firmware-linux-nonfree
        - intel-microcode
        - firmware-realtek
      state: latest
      update_cache: yes
    ignore_errors: yes

  - name: SSH clefs autorisees pour root
    authorized_key:
      user: root
      state: present
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG6VOB6xka5bO3c87sNYtpWIRpswcD+ZPog8iSweokiM

  - name: DNS configuration des resolveurs
    copy:
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
      content: |
        ### /etc/resolv.conf
        nameserver 80.67.169.12
        nameserver 9.9.9.9
        nameserver ns10.fr.dns.opennic.glue
        nameserver 2001:910:800::12
        nameserver 2620:fe::fe

  - name: Locale GB generation des locales
    locale_gen:
      name: en_GB.UTF-8
      state: present
    ignore_errors: yes

  - name: Locale en_GB
    copy:
      dest: /etc/locale.gen
      group: root
      owner: root
      mode: 0644
      content: |
        ### /etc/locale.gen
        en_GB.UTF-8 UTF-8

  - name: Locale en_GB
    command: /usr/sbin/locale-gen

  - name: Locale en_GB
    copy:
      dest: /etc/default/locale
      group: root
      owner: root
      mode: 0644
      content: |
        ### /etc/default/locale
        LC_ALL=C
        # LC_ALL=en_GB.UTF-8
        LANGUAGE=en_GB.UTF-8
        LC_CTYPE="en_GB.UTF-8"
        LC_NUMERIC="en_GB.UTF-8"
        LC_TIME="en_GB.UTF-8"
        LC_COLLATE="en_GB.UTF-8"
        LC_MONETARY="en_GB.UTF-8"
        LC_MESSAGES="en_GB.UTF-8"
        LC_PAPER="en_GB.UTF-8"
        LC_NAME="en_GB.UTF-8"
        LC_ADDRESS="en_GB.UTF-8"
        LC_TELEPHONE="en_GB.UTF-8"
        LC_MEASUREMENT="en_GB.UTF-8"
        LC_IDENTIFICATION="en_GB.UTF-8"

  - name: Locale en_GB
    command: /usr/sbin/update-locale

  - name: BASHRC
    copy:
      dest: "{{ item }}"
      group: root
      owner: root
      mode: 0644
      content: |
        ###  ~/.bashrc
        if [ -f /etc/bashrc ]; then
            . /etc/bashrc
        fi
        if [ -f /etc/bash_completion ]; then
            . /etc/bash_completion
        fi
        #LC_ALL=C
        #PATH=/usr/sbin:/usr/bin:/sbin:/bin
        #export PS1="[\u@\h \w]\\$ "
        #export PS1="\[\e[01;34m\]\u\[\e[0m\]\[\e[01;33m\]@\[\e[0m\]\[\e[01;37m\]\h\[\e[0m\]:\[\e[01;32m\]\w\[\e[0m\] \[\e[01;33m\]\$\[\e[0m\] "
        export PS1="\[\e[01;31m\]\u\[\e[0m\]\[\e[01;33m\]@\[\e[0m\]\[\e[01;37m\]\h\[\e[0m\]:\[\e[01;32m\]\w\[\e[0m\] \[\e[01;33m\]\$\[\e[0m\] "
        alias cp="cp --interactive"
        alias mv="mv --interactive"
        alias rm="rm --interactive"
        alias grep="grep --color=auto"
        alias less="less --quiet"
        alias df="df -h"
        alias dfa="df -haT --total"
        alias du="du --human-readable"
        alias ll="ls -lh --color=auto"
        alias lla="ls -lha --color=auto"
        alias lls="ls -lhS --color=auto"
        alias llt="ls -lht --color=auto"
        alias trees="tree -Csh"
        alias grep="grep --color=auto"
        alias ramclean="sysctl -w vm.drop_caches=3"
        alias ipublic="curl https://api.ipify.org ; echo -e ; curl https://api6.ipify.org"
        alias iperf-free="iperf3 -c ping.online.net -p 5208"
        alias heure="date +'%F %T'"
        alias meteo="curl wttr.in/Paris"
        alias syspatch="apt update && apt dist-upgrade"
        alias sysclean="apt autoclean && apt autoremove"
        export HISTSIZE=999999
        export HISTFILESIZE=999999
        export HISTTIMEFORMAT="%F_%T "
        export VISUAL=vim
        export EDITOR="$VISUAL"
        export PAGER="less"
        export LESS_TERMCAP_mb=$'\e[1;31m'
        export LESS_TERMCAP_md=$'\e[1;33m'
        export LESS_TERMCAP_so=$'\e[01;44;37m'
        export LESS_TERMCAP_us=$'\e[01;37m'
        export LESS_TERMCAP_me=$'\e[0m'
        export LESS_TERMCAP_se=$'\e[0m'
        export LESS_TERMCAP_ue=$'\e[0m'
        export GROFF_NO_SGR=1
    with_items:
      - /root/.bashrc
      - /etc/skel/.bashrc

  - name: VIMRC pour Debian
    copy:
      dest: /etc/vim/vimrc
      group: root
      owner: root
      mode: 0644
      content: |
        """ /etc/vim/vimrc
        syntax on
        set ruler
        set paste
        set number
        set expandtab
        set nocompatible
        set shiftwidth=4
        set softtabstop=4
        set background=dark

  - name: TMUX
    copy:
      dest: "{{ item }}"
      group: root
      owner: root
      mode: 0644
      content: |
        ###  ~/.tmux.conf
        unbind C-b
        set -g prefix C-a
        bind C-a send-prefix
        set -g history-limit 10000
        set -g default-terminal 'screen-256color'
        set -g allow-rename off
        set -g status-style 'bg=black','fg=green','bright'
        set -g window-status-current-style 'bg=green'
        bind s set-window-option synchronize-panes
        #set -g status-bg '#000000'
        #set -g status-fg '#aaaaaa'
        #set -g window-status-current-fg '#008000'
    with_items:
      - /root/.tmux.conf
      - /etc/skel/.tmux.conf

  - name: GitConfig
    copy:
      dest: "{{ item }}"
      group: root
      owner: root
      mode: 0644
      content: |
        ### /root/.gitconfig
        [user]
            name =
            email =
        #   signingkey =
        #[commit]
        #  gpgsign = true
        [core]
            editor = vim
        [color]
            ui = auto
        [alias]
            logp = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
            mg = merge --no-ff
            recup = !sh -c 'git branch --track $1 origin/$1' -
        # [http "https://git.domain.tld/"]
        #   sslVerify = false
        # [http "https://github.com/"]
        #   proxy = "http://User:Password@Proxy:Port"
        # [credential]
        #   helper = cache --timeout 30000
    with_items:
      - /root/.gitconfig
      - /etc/skel/.gitconfig

  - name: GRUB reduction de l'attente
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_TIMEOUT'
      line: GRUB_TIMEOUT=1

  - name: GRUB mise a jour
    command: /usr/sbin/update-grub2

  - name: ETHx configuration
    copy:
      dest: /etc/network/interfaces.ethx
      owner: root
      group: root
      mode: 0644
      content: |
        ### /etc/network/interfaces
        source /etc/network/interfaces.d/*
        auto lo
        iface lo inet loopback
        allow-hotplug ethx
        iface ethx inet dhcp
        iface ethx inet6 auto
        # iface ethx inet static
        # address {{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask }}
        # gateway {{ ansible_default_ipv4.gateway }}

  - name: Redemarrage
    reboot:

  - name: Installation de Gnome Workstation
    apt:
      name:
        - adb
        - audacious
        - bash-completion
        - bzip2
        - ca-certificates
        - certbot
        - chromium
        - curl
        - dnsutils
        - easytag
        - exfalso
        - ffmpeg
        - file-roller
        - firefox-esr
        - gedit
        - git
        - gnome-core
        - gnome-clocks
        - gnome-maps
        - gnome-music
        - gnome-screenshot
        - gnome-tweaks
        - gnome-weather
        - gnupg2
        - gnutls-bin
        - haveged
        - hplip
        - htop
        - iperf3
        - keepassxc
        - libreoffice-gnome
        - libreoffice-gtk3
        - locales
        - nano
        - netcat
        - p7zip-rar
        - rclone
        - rhythmbox
        - rsync
        - s3cmd
        - seahorse
        - snapd
        - sudo
        - tar
        - telnet
        - tmux
        - transmission
        - transmission-cli
        - unrar
        - unzip
        - vim-nox
        - vlc
        - vorbis-tools
        - wget
        - xca
        - xz-utils
      state: latest
      update_cache: yes
    ignore_errors: yes

  - name: Installation des Snaps
    snap:
      name:
        - bitwarden
        - firefox
        - codium
        - opera
        - spotify
    classic: yes

  - name: Redemarrage
    reboot: