---
- hosts: all
  tasks:

  - name: Clavier francais
    copy:
      dest: /etc/default/keyboard
      owner: root
      group: root
      mode: 0644
      content: |
        ### /etc/default/keyboard
        XKBMODEL="dell101"
        XKBLAYOUT="fr"
        XKBVARIANT=""
        XKBOPTIONS=""
        BACKSPACE="guess"

  - name: APT DistUpgrade
    apt:
      upgrade: dist
      update_cache: yes

  - name: APT installation des paquets
    apt:
      name:
        - bash-completion
        - dnsutils
        - bzip2
        - ca-certificates
        - curl
        - htop
        - git
        - gnupg2
        - iperf3
        - nano
        - netcat
        - rsync
        - sudo
        - tar
        - telnet
        - tmux
        - unzip
        - vim-nox
        - wget
        - xz-utils
      state: latest
      update_cache: yes
    ignore_errors: yes

  - name: SSH clefs autorisees pour root
    authorized_key:
      user: root
      state: present
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG6VOB6xka5bO3c87sNYtpWIRpswcD+ZPog8iSweokiM

  - name: IP fixe
    copy:
      dest: /etc/dhcpcd.conf
      owner: root
      group: root
      mode: 0644
      content: |
        define static profile
        profile static_eth0
        static ip_address={{ ansible_default_ipv4.address }}
        netmask={{ ansible_default_ipv4.netmask }}
        static routers={{ ansible_default_ipv4.gateway }}
        static domain_name_servers=9.9.9.9 1.0.0.1

  - name: DNS resolveurs LAN
    copy:
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
      content: |
        ### /etc/resolv.conf
        domain
        nameserver 80.67.169.12
        nameserver 9.9.9.9
        nameserver ns10.fr.dns.opennic.glue
        nameserver 2001:910:800::12
        nameserver 2620:fe::fe

  - name: BASHRC
    copy:
      dest: "{{ item }}"
      group: root
      owner: root
      mode: 0644
      content: |
        ### /root/.bashrc
        if [ -f /etc/bashrc ]; then
            . /etc/bashrc
        fi
        if [ -f /etc/bash_completion ]; then
            . /etc/bash_completion
        fi
        #LC_ALL=C
        #PATH=/usr/sbin:/usr/bin:/sbin:/bin
        #export PS1="[\u@\h \w]\\$ "
        #export PS1="\[\e[01;34m\]\u\[\e[0m\]\[\e[01;33m\]@\[\e[0m\]\[\e[01;37m\]\h\[\e[0m\]:\[\e[01;32m\]\w\[\e[0m\] \[\e[01;33m\]\$\[\e[0m\] "
        #export PS1="\[\e[01;31m\]\u\[\e[0m\]\[\e[01;33m\]@\[\e[0m\]\[\e[01;37m\]\h\[\e[0m\]:\[\e[01;32m\]\w\[\e[0m\] \[\e[01;33m\]\$\[\e[0m\] "
        alias cp="cp --interactive"
        alias mv="mv --interactive"
        alias rm="rm --interactive"
        alias grep="grep --color=auto"
        alias less="less --quiet"
        alias df="df -h"
        alias dfa="df -haT --total"
        alias du="du --human-readable"
        alias ll="ls -lh --color=auto"
        alias lla="ls -lha --color=auto"
        alias lls="ls -lhS --color=auto"
        alias llt="ls -lht --color=auto"
        alias trees="tree -Csh"
        alias grep="grep --color=auto"
        alias ramclean="sysctl -w vm.drop_caches=3"
        alias ipublic="curl ipinfo.io"
        alias iperf-ovh="iperf -c iperf.ovh.net -i 3 -t 10"
        alias heure="date +'%F %T'"
        alias meteo="curl wttr.in/Paris"
        alias sysupdate="apt update && apt dist-upgrade"
        alias sysclean="apt autoclean && apt autoremove"
        export HISTSIZE=99999
        export HISTFILESIZE=99999
        export HISTTIMEFORMAT="%F %T"
        export PAGER="less"
        export LESS_TERMCAP_mb=$'\e[1;31m'
        export LESS_TERMCAP_md=$'\e[1;33m'
        export LESS_TERMCAP_so=$'\e[01;44;37m'
        export LESS_TERMCAP_us=$'\e[01;37m'
        export LESS_TERMCAP_me=$'\e[0m'
        export LESS_TERMCAP_se=$'\e[0m'
        export LESS_TERMCAP_ue=$'\e[0m'
        export GROFF_NO_SGR=1
    with_items:
      - /root/.bashrc
      - /etc/skel/.bashrc

  - name: VIMRC pour Debian
    copy:
      dest: /etc/vim/vimrc
      group: root
      owner: root
      mode: 0644
      content: |
        """ /etc/vim/vimrc
        syntax on
        set ruler
        set paste
        set number
        set expandtab
        set nocompatible
        set shiftwidth=4
        set softtabstop=4
        set background=dark

  - name: TMUX
    copy:
      dest: /root/.tmux.conf
      group: root
      owner: root
      mode: 0644
      content: |
        ###  ~/.tmux.conf
        unbind C-b
        set -g prefix C-a
        bind C-a send-prefix
        set -g history-limit 1000000
        set -g default-terminal 'screen-256color'
        set -g allow-rename off
        set -g base-index 1
        set -g status-position top
        set -g status-fg colour250
        set -g status-bg colour235
        set -g status-attr dim
        set -g pane-active-border-fg colour8
        set -g pane-active-border-bg default
        set -g mouse on
        set -g status-right '#H | %F | %T '
        set-window-option -g window-status-current-fg colour15
        set-window-option -g window-status-current-bg colour0
        bind s set-window-option synchronize-panes

  - name: GitConfig
    copy:
      dest: /root/.gitconfig
      group: root
      owner: root
      mode: 0644
      content: |
        ### /root/.gitconfig
        [user]
            name =
            email =
        [core]
            editor = vim
        [color]
            ui = auto
        [alias]
            logp = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
            mg = merge --no-ff
            recup = !sh -c 'git branch --track $1 origin/$1' -

  - name: Locale GB generation des locales
    locale_gen:
      name: en_GB.UTF-8
      state: present
    ignore_errors: yes

  - name: Locale GB edition du fichier de configuration
    copy:
      dest: /etc/environment
      group: root
      owner: root
      mode: 0644
      content: |
        ### /etc/environment
        LANG=en_GB.UTF-8
        LC_CTYPE=en_GB.UTF-8
        LC_NUMERIC="en_GB.UTF-8"
        LC_TIME="en_GB.UTF-8"
        LC_COLLATE="en_GB.UTF-8"
        LC_MONETARY="en_GB.UTF-8"
        LC_MESSAGES="en_GB.UTF-8"
        LC_PAPER="en_GB.UTF-8"
        LC_NAME="en_GB.UTF-8"
        LC_ADDRESS="en_GB.UTF-8"
        LC_TELEPHONE="en_GB.UTF-8"
        LC_MEASUREMENT="en_GB.UTF-8"
        LC_IDENTIFICATION="en_GB.UTF-8"
        LC_ALL=en_GB.UTF-8

  - name: Locale GB edition du fichier de configuration
    copy:
      dest: /etc/locale.conf
      group: root
      owner: root
      mode: 0644
      content: |
        ### /etc/locale.conf
        LANG=en_GB.UTF-8

  - name: Locale GB configuration
    command: '/usr/bin/localectl set-locale LANG=en_GB.UTF-8 && /usr/sbin/locale-gen && /usr/sbin/update-locale en_GB.UTF-8'
    ignore_errors: yes

  - name: Services WPA desactive
    systemd:
      name: wpa_supplicant.service
      state: stopped
      enabled: no
      masked: no
      daemon_reload: yes
    ignore_errors: yes

  - name: Redemarrage
    reboot: